// example/example-vue/src/components/ConnectorCard.vue
<template>
  <div class="card">
    <div class="card-header">
      <!--      <div class="connector-logo" v-html="provider.logo"></div>-->
      <h2>{{ connector.name }}</h2>
    </div>

    <div class="card-body">
      <ConnectorCardTable :connector="connector"/>
      <button @click="connector.status === 'connected' ? connector.disconnect() : connect()">
        {{ label[connector.status] }}
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent, PropType} from 'vue';
import ConnectorCardTable from "@/components/ConnectorCardTable.vue";
import {ChainIdNotAllowedError, ConnectorStatus, type IConnectorWrapper} from "@whitelabel-solutions/wallet-connector";

export default defineComponent({
  name: 'ConnectorCard',
  components: {ConnectorCardTable},
  props: {
    connector: Object as PropType<IConnectorWrapper>,
  },
  setup({connector}){
    const connect = async () => {
      await connector?.connect()
      if(connector?.error instanceof ChainIdNotAllowedError){
        console.warn("Invalid Chainid")
      }
    }

    const label = {
      [ConnectorStatus.LOADING]: "Loading",
      [ConnectorStatus.CONNECTED]: "Disconnect",
      [ConnectorStatus.DISCONNECTED]: "Connect",
      [ConnectorStatus.ERROR]: "Try Again"
    }

    return {connect, label}
  }
});
</script>

<style scoped>
button {
  display: block;
  padding: 10px;
  margin-top: 16px;
  width: 100%;
  border: none;
  border-radius: 4px;
  background-color: #f3f3f3;
  cursor: pointer;
}
</style>

// packages/example-react/src/components/ConnectorCard.js
import StatusIndicator from "./StatusIndicator";
import {ChainIdNotAllowedError} from "@whitelabel-solutions/wallet-connector";

function ConnectorCardTable({connector}) {
    return (
        <table>
            <tbody>
            <tr>
                <td>Id</td>
                <td>
                    {connector?.id}
                </td>
            </tr>
            <tr>
                <td>Status</td>
                <td>
                    <StatusIndicator
                        connected={connector.connected}
                        error={!!connector.error}
                        loading={connector.loading}/>
                </td>
            </tr>
            <tr>
                <td>Selected Account</td>
                <td>{connector?.selectedAccount ?? 'None'}</td>
            </tr>
            <tr>
                <td>Error</td>
                <td>{connector.error ? connector.error.message : 'None'}</td>
            </tr>
            <tr>
                <td>Chain Id</td>
                <td>{connector?.chainId ?? 'None'}</td>
            </tr>
            </tbody>
        </table>)
}

export default function ConnectorCard({connector}) {
    const connect = async () => {
        console.log("connect")
       const res = await connector?.connect()
        console.log("connected?", res)
        if (connector?.error instanceof ChainIdNotAllowedError) {
            console.warn("Invalid Chainid")
        }
    }

    const label = connector?.connected ? "Disconnect" :
        (connector?.loading ? "Loading" :
            (connector?.error ? "Try Again" : "Connect"))

    return (<div className="card">
            <div className="card-header">
                <h2>{connector.name}</h2>
            </div>

            <div className="card-body">
                <ConnectorCardTable connector={connector}/>
                <button onClick={() => connector.connected ? connector.disconnect() : connect()}>
                    {label}
                </button>
            </div>
        </div>
    )
}
